import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/custom/header";
import StoreProvider from "./StoreProvider";

import Refresher from "@/components/custom/refresher";
import QueryProvider from "./QueryProvider";
import { Toaster } from "react-hot-toast";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <StoreProvider>
        <body className="antialiased font-sans">
          <QueryProvider>
            <Refresher>
              <Header />
              <main>{children}</main>
              <Toaster />
            </Refresher>
          </QueryProvider>
        </body>
      </StoreProvider>
    </html>
  );
}
