import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope } from "next/font/google";
import "./globals.css";
import Header from "@/components/custom/header";
import StoreProvider from "./StoreProvider";
import { Toaster } from "@/components/ui/sonner"
 
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <StoreProvider>
        <body
        className={`${geistSans.variable} ${geistMono.variable} ${manrope.variable} antialiased font-sans`}
      >
        <Header />
        <main>{children}</main>
           <Toaster />
      </body>
    </StoreProvider>
    </html>
  );
}
